language: ruby
sudo: false
cache: bundler
script: 'bundle exec rake test:coverage --trace && bundle exec rubocop --display-cop-names'
before_install:
  - gem install bundler
  - gem update bundler
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-9.0.5.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
